version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: 'America/Los_Angeles'  # Adjust timezone as needed
      WEBPASSWORD: 'Your Password'
    volumes:
      - '/tmp/mountd/disk1_part1/docker/pihole/etc/pihole/:/etc/pihole/'
      - '/tmp/mountd/disk1_part1/docker/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      lan:
        ipv4_address: 192.168.8.3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

networks:
  lan:
    external:
      name: macvlan_lan
